### ISSUE TITLE
Um....

### ISSUE THREAD

**Issue by sithsiri** [tymmc2/CodeClubWalsh#3]
How does one make this into a website?

**Comment by tymmc2** [comment]
Will find out!

**Comment by sithsiri** [comment]
Leave this open so that someone can help us.

**Comment by tymmc2** [comment]
K

**Comment by sithsiri** [comment]
http://tymmc2.github.io/CodeClubWalsh/
All we have to do is merge into the gh-pages branch, using gh-pages as base and master as the compare. It will add changes from master to gh-pages when we do that.
